#!/bin/bash
#login to azure
az login

sudo docker login ccContainerRegistry1.azurecr.io --username 0c2f4e50-746a-4535-b368-cae13522a34b --password q0yg-Hknd4yPUtTn.6y.3e_Gp7gKqeJ0un

sudo cp /root/.docker/config.json ~/

sudo chmod 777 ~/config.json

kubectl create secret generic docker-secret-1 --type=kubernetes.io/dockerconfigjson --from-file .dockerconfigjson=/home/ubuntu/config.json --kubeconfig ../Terraform/kubeconfig

#install kubectl
az aks install-cli

az aks get-credentials --resource-group CC-Group-Resources --name cc-cluster

#login to docker
sudo docker login ccContainerRegistry1.azurecr.io

#terraform

SUBSCRIPTION_ID=5cdec30a-3c78-4458-9e5b-75ad003e133c \

az ad sp create-for-rbac \
  --role="Contributor" \
  --scopes="/subscriptions/$SUBSCRIPTION_ID"

#{
#  "appId": "0c2f4e50-746a-4535-b368-cae13522a34b",
#  "displayName": "azure-cli-2021-11-08-08-49-27",
#  "name": "0c2f4e50-746a-4535-b368-cae13522a34b",
#  "password": "q0yg-Hknd4yPUtTn.6y.3e_Gp7gKqeJ0un",
#  "tenant": "44e3cf94-19c9-4e32-96c3-14f5bf01391a"
#}

export ARM_CLIENT_ID=0c2f4e50-746a-4535-b368-cae13522a34b
export ARM_SUBSCRIPTION_ID=5cdec30a-3c78-4458-9e5b-75ad003e133c
export ARM_TENANT_ID=44e3cf94-19c9-4e32-96c3-14f5bf01391a
export ARM_CLIENT_SECRET=q0yg-Hknd4yPUtTn.6y.3e_Gp7gKqeJ0un

#inside the terraform folder

terraform init
terraform plan
terraform apply

./deployFrontend
./deployBackend
./deployDB

