- apiVersion: v1
  kind: deployment
  metadata:
    name: frontend-app
  spec:
    finalizers:
      - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-app
    namespace: login-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: frontend-app
    template:
      metadata:
        labels:
          app: frontend-app
      spec:
        nodeSelector:
          beta.kubernetes.io/os: linux
        containers:
          - name: frontend-app
            image: cccontainerregistry1.azurecr.io/frontend:latest
            env:
              - name: ALLOW_EMPTY_PASSWORD
                value: 'yes'
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi
            ports:
              - containerPort: 80
                name: redis
- apiVersion: v1
  kind: Service
  metadata:
    name: frontend-back
    namespace: login-app
  spec:
    ports:
      - port: 6379
    selector:
      app: frontend-back
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: frontend-app
    namespace: login-app
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: frontend-app
    template:
      metadata:
        labels:
          app: frontend-app
      spec:
        nodeSelector:
          beta.kubernetes.io/os: linux
        containers:
          - name: frontend-app
            image: cccontainerregistry1.azurecr.io/frontend:latest
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi
            ports:
              - containerPort: 80
            env:
              - name: REDIS
                value: frontend-back
- apiVersion: v1
  kind: Service
  metadata:
    name: frontend-app
    namespace: login-app
  spec:
    type: LoadBalancer
    ports:
      - port: 80
    selector:
      app: frontend-app
