apiVersion: v1
kind: Pod
metadata:
  name: backend
spec:
  containers:
  - name: backend
    image: cccontainerregistry1.azurecr.io/it18009446@my.sliit.lk/backend:latest
  imagePullSecrets:
  - name: docker-secret

